#!/bin/sh

rexx txt2pdf config acmeit.conf
exit

   IN acmeit.txt \
   OUT acmeit.pdf \
   IFEMPTY blank \
   ORIENT port \
   LM 1.5 TM 1.5 RM .5 BM .5 \
   PAPER 8.5x11/GrayBar \
   IMAGE load/logo/acmeit.jpg \
   IMAGE draw/logo/0/720/80 \
   BG \"tmark/bu/black/blue/10/80/  Sample  \" \
   DRAW rect/72/720/612/792/100//black \
   DRAW \"text/115/730/tb/80//blue/red/2/Bevel//150/Acme IT\" \
   DRAW rect/0/0/72/720/100//ff3333 \
   DRAW \"text/47/63/hi/30///black/2/Bevel/90/200/We Know Mainframes\" \
   DRAW \"text/45/65/hi/30///silver/2/Bevel/90/200/We Know Mainframes\" \
   DRAW line/72/0/612/720/100/Olive/1 \
   DRAW line/72/0/612/720/100/yellow/4//2/10 \
   DRAW line/72/720/612/0/100/green/3/Round/0/6

